
from enum import Enum

class PostmanStates(Enum):
    """All possible status codes for the Postman Family.
    """
    SERVICE_READY = "220"
    SERVICE_CLOSING_TRANSIMISSION_CHANNEL = "221"
    AUTHENTICATION_SUCCEEDED = "235"
    REQUEST_MAIL_ACTION_OKAY = "250"
    SERVER_BASE64_ENCODED_CHALLENGE = "334"
    START_MAIL_INPUT = "354"
    SERVICE_NOT_AVAILABLE = "421"
    COMMAND_UNRECOGNIZED = "500"
    SYNTAX_ERROR_IN_PARAMETERS_OR_ARUGUMENTS = "501"
    BAD_SEQUENCE_OF_COMMANDS = "503"
    COMMAND_PARAMETER_NOT_IMPLEMENTED = "504"
    AUTHENTICATION_CREDENTIALS_INVALID = "535"
